---
kind: Service
apiVersion: v1
metadata:
  name: auth-server-service
spec:
  selector:
    # Should match the template.metadata.labels.app value
    app: oauth-server
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 7777
      name: http
  type: ClusterIP