---
kind: Service
apiVersion: v1
metadata:
  name: user-server-service
spec:
  selector:
     # Should match the template.metadata.labels.app value
    app: user-service
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 7003
      # Port accessible outside cluster
      nodePort: 30002
      name: http
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
spec:
  selector:
    matchLabels:
        app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sajursn/user:one
          #same port as mentioned in applciations application.properties
          ports:
            - containerPort: 7003
          readinessProbe:
              httpGet:
                path: /actuator/health
                port: 7003
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 3
              failureThreshold: 1
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 7003
              initialDelaySeconds: 20
              timeoutSeconds: 2
              periodSeconds: 8
              failureThreshold: 1