INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'READ_EMPLOYEE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'READ_ALL_EMPLOYEE');

INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'CREATE_EMPLOYEE');

INSERT INTO ROLE_(ID, NAME) VALUES (1,'ROLE_ADMIN');
INSERT INTO ROLE_(ID, NAME) VALUES (2,'ROLE_USER');

INSERT INTO ROLES_AUTHORITIES(ROLE_ID,AUTHORITY_ID) VALUES(1,1);
INSERT INTO ROLES_AUTHORITIES(ROLE_ID,AUTHORITY_ID) VALUES(1,2);
INSERT INTO ROLES_AUTHORITIES(ROLE_ID,AUTHORITY_ID) VALUES(1,3);

INSERT INTO ROLES_AUTHORITIES(ROLE_ID,AUTHORITY_ID) VALUES(2,1);



INSERT INTO USER_(ID, USER_NAME, PASSWORD, ENABLED)
VALUES (1, 'john', /*secret*/'$2a$10$krDTAgKDLpHHbzcngFn2suQ/RNyrf7AOLT8WeX5GftzD4cjIv2pv.', TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ENABLED)
VALUES (2, 'tom',  /*secret*/'$2a$10$krDTAgKDLpHHbzcngFn2suQ/RNyrf7AOLT8WeX5GftzD4cjIv2pv.', TRUE);
  
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (1, 2);

INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (2, 1);